package player.sazzer;

public enum AudioServiceAction {
    AUDIO_SERVICE_ACTION_UPDATE_PROGRESS,
    AUDIO_SERVICE_ACTION_UPDATE_BINDER,
    AUDIO_SERVICE_ACTION_TOGGLE_PLAY,
    AUDIO_SERVICE_ACTION_NEXT_SONG,
    AUDIO_SERVICE_ACTION_PREV_SONG,
    AUDIO_SERVICE_ACTION_CLEAN_QUEUE,
    AUDIO_SERVICE_ACTION_UPDATE_SONG_ID,
    AUDIO_SERVICE_ACTION_PLAY_SONG,
    AUDIO_SERVICE_ACTION_EXPORT_QUEUE_TO_PLAYLIST,
    // Actions to obtain from the AudioQueue class
    AUDIO_SERVICE_ACTION_FETCH_SONGS,
    AUDIO_SERVICE_ACTION_FETCH_ALBUMS,
    AUDIO_SERVICE_ACTION_OBTAIN_SONGS_TO_DISPLAY,
    AUDIO_SERVICE_ACTION_OBTAIN_ALBUMS_TO_DISPLAY,
    AUDIO_SERVICE_ACTION_UPDATE_DETAILED_INFO,

}
