package player.sazzer;

public enum AudioServiceAction {
    AUDIO_SERVICE_ACTION_UPDATE_PROGRESS,
    AUDIO_SERVICE_ACTION_UPDATE_BINDER,
    AUDIO_SERVICE_ACTION_TOGGLE_PLAY,
    AUDIO_SERVICE_ACTION_NEXT_SONG,
    AUDIO_SERVICE_ACTION_PREV_SONG,
}
